services:
  - type: web
    name: hackrx-insurance-api
    env: python
    plan: free # Can be upgraded for more power
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: HACKRX_API_KEY
        fromSecret: true